pesquisasatisfacao/accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.i18n import JavaScriptCatalog

from pesquisasatisfacao.accounts import views
from pesquisasatisfacao.accounts.views import GeneratePDF

app_name = 'accounts'


urlpatterns = [
    path('', include('django.contrib.auth.urls')),

    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),

    path('login/', auth_views.auth_login, {'template_name': 'registration/login.html'}, name='login'),
    path('accounts/registro/', views.register, name='register'),

    path('accounts/horario/', views.schedule, name='schedule'),

    path('accounts/ficha/listar/', views.work_schedule_list, name='work_schedule_list'),
    path('accounts/ficha/nova/', views.work_schedule_create, name='work_schedule_create'),
    path('accounts/ficha/<int:id>/editar/', views.work_schedule_update, name='work_schedule_update'),

    path('<int:id>/', GeneratePDF.as_view(), name='generatepdf'),
    path('<int:id>/pdf/', views.admin_receipt_pdf, name='admin_receipt_pdf'),



    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

pesquisasatisfacao/core/urls.py
from django.urls import path, include
from material.frontend import urls as frontend_urls

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('', include(frontend_urls)),

    path('representacao/novo/', views.person_representative_create, name='person_representative_create'),
    path('representacao/<int:pk>/editar/', views.person_representative_update, name='person_representative_update'),
    path('representacao/listar/', views.person_representative_list, name='person_representative_list'),


    path('cliente/novo/', views.person_client_create, name='person_client_create'),
    path('cliente/<int:pk>/editar/', views.person_client_update, name='person_client_update'),
    path('cliente/popular/', views.person_populate, name='person_populate'),
    path('cliente/listar/', views.person_client_list, name='person_client_list'),
    path('cliente/<int:pk>/pesquisas/', views.person_client_detail, name='person_client_detail'),

    # Usa a mesma view de cliente




    path('pergunta/nova/', views.question_create, name='question_create'),
    path('pergunta/<int:pk>/editar/', views.question_update, name='question_update'),
    path('pergunta/popular/', views.question_populate, name='question_populate'),
    path('perguntas/listar/', views.question_list, name='question_list'),

    path('pesquisa/nova/', views.seach_create, name='seach_create'),
    path('pesquisa/criar/', views.pesquisa_create, name='pesquisa_create'),
    path('pesquisa/<int:pk>/editar/', views.pesquisa_update, name='pesquisa_update'),
    path('pesquisa/listar/', views.search_list, name='search_list'),

    path('pesquisa/dash/', views.question_level_view, name='question_level_view'),
    path('pesquisa/dash2/', views.question_level_view2, name='question_level_view2'),
]

pesquisasatisfacao/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pesquisasatisfacao.core.urls')),
    path('', include('pesquisasatisfacao.accounts.urls')),
    path('admin/', admin.site.urls),
]

pesquisasatisfacao/core/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    name = models.CharField('Nome', max_length=100)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('person_client_detail', args=[str(self.pk)])


class Client(models.Model):
    cdalterdata = models.IntegerField('Cód. Alterdata', db_index=True, unique=True)
    name = models.CharField('Nome', max_length=100)
    phone = models.CharField('Telefone', max_length=50, null=True, blank=True)
    cpf_cnpj = models.CharField('CPF/CNPJ', max_length=18, null=True, blank=True)
    email = models.CharField('E-Mail', max_length=50, null=True, blank=False)
    # system = models.CharField('Sistema', max_length=10, null=True, blank=False)
    cep = models.CharField('Cep', max_length=10, null=True, blank=False)
    logradouro = models.CharField('Logradouro', max_length=100)
    numero = models.CharField('Número', max_length=10, null=False, blank=False)
    bairro = models.CharField('Bairro', max_length=50, null=False, blank=False)
    cidade = models.CharField('Cidade', max_length=50, null=False, blank=False)
    estado = models.CharField('Estado', max_length=10, null=False, blank=False)
    is_representative = models.BooleanField('É representante?', default=False)
    representative = models.ForeignKey("self", null=True, blank=True, related_name="children", on_delete=models.CASCADE,
                                       verbose_name="Representante")
    products = models.ManyToManyField('core.product', related_name="products", verbose_name="Produtos")
    last_search = models.CharField('Última pesquisa.', max_length=11, null=True, blank=True)
    created_on = models.DateField(
        'Criado em.',
        auto_now_add=True,
        auto_now=False
    )

    class Meta:
        ordering = ('created_on',)
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    def save(self, *args, **kwargs):
        self.email = self.email.lower()
        self.logradouro = self.logradouro.upper()
        self.bairro = self.bairro.upper()
        self.cidade = self.cidade.upper()
        self.estado = self.estado.upper()

        super(Client, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('person_client_detail', args=[str(self.pk)])


class Question(models.Model):
    LEVEL_CHOICES = (
        ('0', 'Dependencia'),
        ('1', 'Confianca'),
        ('2', 'Comprometimento'),
        ('3', 'Preditiva'),
    )
    question = models.CharField('Pergunta', max_length=200)
    level = models.CharField('Nível', max_length=15,
                             choices=LEVEL_CHOICES, default='0')

    class Meta:
        verbose_name = 'Questão'
        verbose_name_plural = 'Questões'
        ordering = ('-level',)

    def __str__(self):
        return self.question

    def get_absolute_url(self):
        return reverse('question_update', args=[str(self.pk)])


class Search(models.Model):
    search_key = models.CharField(
        'Período', max_length=200, db_index=False)
    person = models.ForeignKey(
        'core.client', related_name='Cliente', on_delete=models.CASCADE)
    researched = models.CharField('Entrevistado', max_length=200)
    participation_on = models.DateField(
        'Período da pesquisa',
        auto_now_add=True,
        auto_now=False
    )
    created_on = models.DateTimeField(
        'Solicitado em',
        auto_now_add=True,
        auto_now=False
    )

    class Meta:
        verbose_name = 'Pesquisa'
        verbose_name_plural = 'Pesquisas'
        unique_together = (('search_key', 'person'),)
        ordering = ('-participation_on',)

    def get_absolute_url(self):
        return reverse('pesquisa_update', args=[str(self.pk)])

    # def get_absolute_url(self):
    #     return reverse('catalog:category_list', kwargs={'slug': self.slug})

    def __str__(self):
        return self.search_key


# def post_save_search(sender, instance, created,  **kwargs):
#     if created:
#         questions = Question.objects.all()
#         # search = Search.objects.filter(pk=instance.pk)
#
#         lista = []
#
#         # print(worksheet.nrows)
#         for question in questions:
#             print('search_id=', instance.pk, 'question_id=', question.pk)
#             lista.append(
#                 SearchItem(search_id=instance.pk,
#                            question_id=question.pk,
#                            response=False,
#                            )
#             )
#
#         SearchItem.objects.bulk_create(lista)
#
#
# models.signals.post_save.connect(
#     post_save_search, sender=Search, dispatch_uid='post_save_search'
# )


class SearchItem(models.Model):
    search = models.ForeignKey(
        'core.search', related_name='Periodo', on_delete=models.CASCADE, verbose_name="Período da Pesquisa")
    question = models.ForeignKey(
        'core.question', related_name='Pergunta', on_delete=models.CASCADE, verbose_name="Pergunta")
    response = models.BooleanField('Resposta')

    class Meta:
        verbose_name = 'Pesquisa Detalhe'
        verbose_name_plural = 'Pesquisas Detalhe'
        unique_together = (('search', 'question'),)
        ordering = ('-question',)

    def __str__(self):
        return self.question.question

pesquisasatisfacao/core/forms.py
from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from material import *

from pesquisasatisfacao.core.models import Client, Question, Search, SearchItem, Product
from django.forms import inlineformset_factory

#
# class PersonForm(forms.ModelForm):
#
#     class Meta:
#         model = Person
#         fields = (
#             'cdalterdata',
#             'name',
#             'phone',
#         )
#
#     layout = Layout(
#         Fieldset("Inclua uma Pessoa",
#                  Row(Span4('cdalterdata'),Span8('name'), ),
#                  Row('phone')
#                  )
#     )
SYSTEM_CHOICES = (
    ('0', 'Pack'),
    ('1', 'Shop'),
    ('2', 'IShop'),
    ('3', 'Immobile'),
    ('4', 'Bimer'),
)


class ClientForm(forms.ModelForm):

    representative = forms.ModelChoiceField(queryset=Client.objects.filter(is_representative=True), required=False,
                                            label="Representante (Matriz ou Filial)", )

    class Meta:
        model = Client
        fields = (
            'cdalterdata',
            'name',
            'phone',
            'cpf_cnpj',
            'email',
            'cep',
            'logradouro',
            'numero',
            'bairro',
            'cidade',
            'estado',
            'representative',
            'last_search',
            'products',
        )
        exclude = ('is_representative',)

    layout = Layout(
        Fieldset("Cadastro de Cliente",
                 Row(Span3('cdalterdata'), Span9('name'), ),
                 Row(Span12('representative'), ),
                 Row(Span4('phone'), Span8('cpf_cnpj')),
                 Row(Span9('email'), Span3('last_search'), ),
                 Row(Span12('products'), ),
                 ),
        Fieldset('Endereço',
                 Row(Span2('cep'), Span8('logradouro'), Span2('numero')),
                 Row(Span5('bairro'), Span5('cidade'), Span2('estado')))
        )


class RepresentativeForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = (
            'cdalterdata',
            'name',
            'phone',
            'cpf_cnpj',
            'email',
            'cep',
            'logradouro',
            'numero',
            'bairro',
            'cidade',
            'estado',
            'products',
        )
        exclude = ('representative', 'is_representative', 'last_search',)

    layout = Layout(
        Fieldset("Cadastro de Filial ou Representação",
                 Row(Span3('cdalterdata'), Span9('name'), ),
                 Row(Span4('phone'), Span8('cpf_cnpj')),
                 Row(Span5('email'), Span7('products'), ),
                 ),
        Fieldset('Endereço',
                 Row(Span2('cep'), Span8('logradouro'), Span2('numero')),
                 Row(Span5('bairro'), Span5('cidade'), Span2('estado')))
        )


class QuestionForm(forms.ModelForm):

    level = forms.ChoiceField(
        choices=(
            ('0', 'Dependencia'),
            ('1', 'Confianca'),
            ('2', 'Comprometimento'),
            ('3', 'Preditiva'),),

        label='Escolha o nível',

        widget=forms.RadioSelect)

    class Meta:
        model = Question
        fields = (
            'question',
            'level',
        )

    layout = Layout(
        Fieldset("Inclua uma Pergunta",
                 Row('question', ),
                 Row('level')
                 )
    )


class SearchFormCompleto(forms.ModelForm):

    class Meta:
        model = Search
        fields = (
            'search_key',
            'person',
            'researched',
        )


class SearchForm(forms.ModelForm):

    class Meta:
        model = Search
        fields = '__all__'
        exclude = ()

    layout = Layout(
        Fieldset("Responda com Calma.", Row('person', 'search_key'), Row('researched',),))


SearchItemFormSet = inlineformset_factory(Search, SearchItem,
                                          widgets={'question__name': forms.TextInput(attrs={'width': '110%'}), },
                                          exclude=('id',),
                                          can_delete=True,
                                          fields=('question', 'response'), extra=1)

pesquisasatisfacao/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    {% block css %}
        <!-- Compiled and minified CSS -->
        <!--O PROBLEMA É O CSS MATERIAL ABAIXO QUE NÃO FUNCIONA COM JQUERY-->
        {% include 'material/includes/material_css.html' %}
        <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
        <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/smoothness/jquery-ui.css">

    {% endblock %}

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>PESQUISA</title>


</head>

<body>

    <!-- Dropdown Structure -->
    <ul id="drp_clientes" class="dropdown-content">
      <li><a href="{% url 'person_client_create' %}"><i class="material-icons">person</i>Novo Cliente</a></li>
      <li><a href="{% url 'person_client_list' %}"><i class="material-icons">format_list_bulleted</i>Lista Clientes</a></li>
      <li class="divider"></li>
      <li><a href="{% url 'accounts:work_schedule_create' %}"><i class="material-icons">date_range</i>Cadastro Ficha</a></li>
      <li><a href="{% url 'accounts:work_schedule_list' %}"><i class="material-icons">format_list_bulleted</i>Listar Fichas</a></li>
      <li><a href="#!">em breve...</a></li>
    </ul>

    <ul id="drp_questions" class="dropdown-content">
      <li><a href="{% url 'question_create' %}"><i class="material-icons">question_answer</i>Cadastrar nova Pergunta</a></li>
      <li><a href="{% url 'question_list' %}"><i class="material-icons">format_list_bulleted</i>Lista de Perguntas</a></li>
      <li class="divider"></li>
      <li><a href="#!">em breve...</a></li>
    </ul>

    <ul id="drp_representative" class="dropdown-content">
      <li><a href="{% url 'person_representative_create' %}"><i class="material-icons">person_pin</i>Novo Representante</a></li>
      <li><a href="{% url 'person_representative_list' %}"><i class="material-icons">format_list_bulleted</i>Lista Representantes</a></li>
      <li class="divider"></li>
      <li><a href="#!">em breve...</a></li>
    </ul>

    <!--NAVBAR-->
    <nav class="#1a237e indigo darken-4 col s12 m6">
        <div class="nav-wrapper">
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
        <a href="" class="brand-logo">Alterdata Filiais</a>
            <ul class="right hide-on-med-and-down">
            <li><a class="dropdown-trigger" href="#!" data-target="drp_clientes">Clientes<i class="material-icons right">arrow_drop_down</i></a></li>
            <li><a class="dropdown-trigger" href="#!" data-target="drp_questions">Pesquisa<i class="material-icons right">arrow_drop_down</i></a></li>
            <li><a class="dropdown-trigger" href="#!" data-target="drp_representative">Representantes<i class="material-icons right">arrow_drop_down</i></a></li>

            {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'accounts:register' %}">Cadastre-se</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
            {% endif %}


            </ul>
        </div>
    </nav>

    <!--SIDENAV-->
    <ul id="slide-out" class="sidenav">
        <li>
            <div class="user-view">
                <div class="background">
                    <img src="{% static 'img/ocean.jpg' %}" alt=""/>
                </div>

                <img src="{% static 'img/person1.jpg' %}" alt="" class="circle"/>
                <a href="#name"><span class="white-text name">John Doe</span></a>
                <a href="#email"><span class="white-text email">jdandturk@gmail.com</span></a>
            </div>
        </li>

        <li><a href="{% url 'person_client_create' %}"><i class="material-icons">perm_identity</i>Cliente</a></li>
        <li><a href="{% url 'person_client_list' %}"><i class="material-icons">list</i>Lista Clientes</a></li>
        <li><a href="{% url 'question_create' %}"><i class="material-icons">question_answer</i>Cadastrar nova Pergunta</a></li>
        <li><a href="{% url 'question_list' %}"><i class="material-icons">question_answer</i>Lista de Perguntas</a></li>
        <li><a href="{% url 'accounts:work_schedule_create' %}"><i class="material-icons">date_range</i>Cadastro Ficha</a></li>
        <li><a href="#!">Em breve...</a></li>
        <li><div class="divider"></div></li>
        <li><a class="subheader">Subheader</a></li>
        <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
    </ul>

    <div class="container">

        <!--BLOCO CONTAINER   -->
        {% block container %}
            <p>Use this document as a way to quick start any new project.</p>
        {% endblock container %}


    </div> <!-- /container -->

    {% block js %}
        <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
        <script src="{% static 'js/jquery.mtz.monthpicker.js' %}"></script>
        <script src="https://code.highcharts.com/highcharts.src.js"></script>


    <!-- Compiled and minified JQuery -->
        <!--<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>-->
        <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>-->

        <!-- Compiled and minified JavaScript -->
        {% include 'material/includes/material_js.html' %}


        <script>
            $(document).ready(function(){
                //MATERIALIZE
                $('.sidenav').sidenav();
                $('.dropdown-trigger').dropdown({ hover: true, constrainWidth: false });
                $('.fixed-action-btn').floatingActionButton();
                $('.datepicker').datepicker(
                    {
                        showClearBtn:false,
                        autoClose:true,
                        setDefaultDate:true,
                        //POSSO SETAR 01/mm/yyyy OU REMOVER ESSE CAMPO DO MODELO E PREENCHER COM SIGNALS
                        format: 'dd/mm/yyyy',
                            i18n: {
                                months: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
                                monthsShort: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
                                weekdays: ["Domingo","Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
                                weekdaysShort: ["Dom","Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
                                weekdaysAbbrev: ["D","S", "T", "Q", "Q", "S", "S"]
                            }
                        }
                    );

                // JQUERY MTZ.MONTHPICKER
                //https://www.jqueryscript.net/time-clock/jQuery-Plugin-For-jQuery-UI-Month-Year-Picker-mtz-monthpicker.html



                $('.monthpicker').monthpicker({
                    pattern: 'mm/yyyy',
                    monthNames: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
                });
            });
        </script>
        <script src="{% static '/js/cep.js' %}"></script>
    {% endblock %}

</body>

</html>

pesquisasatisfacao/core/templates/dash.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}
{% block container %}

<div class="card larger" id="card-radius">
<div id="representacao"></div>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script>
      Highcharts.chart('representacao', {
          chart: {
              type: 'column'
          },
          title: {
              text: 'Respostas geradas no total.'
          },
          xAxis: {
              categories: {{ categories|safe }}
          },
          series: [{
              name: 'Respostas Sim',
              data: {{ true_series }},
              color: 'green'
          }, {
              name: 'Respostas Não',
              data: {{ false_series }},
              color: 'red'
          }]
      });
    </script>
</div>
{% endblock %}

pesquisasatisfacao/core/templates/dash2.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}
{% block container %}

<div class="card larger" id="card-radius">
<div id="representacao"></div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script>
  Highcharts.chart('representacao', {{ chart|safe }});
</script>
</div>
{% endblock %}

pesquisasatisfacao/core/templates/person_client_detail.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}
{% block container %}

<div class="card larger" id="card-radius">

    {% for client in clients %}
        <div class="fixed-action-btn click-to-toggle">
            <a class="btn-floating btn-large red">
                <i class="large material-icons">add</i>
            </a>
            <ul>
                <li><a href="{% url 'seach_create' %}" class="btn-floating red"><i class="material-icons">event</i></a></li>
                <li><a href="{% url 'person_client_update' pk=client.id %}" class="btn-floating yellow darken-1"><i class="material-icons">person</i></a></li>
                <li><a href="{% url 'person_client_list' %}" class="btn-floating green"><i class="material-icons">list</i></a></li>
                <li><a href="{% url 'question_list' %}" class="btn-floating blue"><i class="material-icons">question_answer</i></a></li>
            </ul>
        </div>


        <div class="card-panel #424242 grey darken-3 center" id="title-panel">{{client.name}}</div>
    {% empty %}

    {% endfor %}



    <table>
        <thead class="#cfd8dc blue-grey lighten-4">
            <tr>
                <th class="center-align">ID</th>
                <th>Período</th>
                <th>Entrevistado</th>
            </tr>
        </thead>

        <tbody>
            {% for search in searchs %}
                <tr>
                    <td class="center-align">
                        <a href="{% url 'pesquisa_update' pk=search.id %}">{{ search.id|linebreaks }}</a>
                    </td>

                    <td>
                        <a href="{% url 'pesquisa_update' pk=search.id %}">{{ search.search_key|linebreaks }}</a>
                    </td>


                    <td>{{ search.researched }}</td>
                </tr>
            {% empty %}
                <div class="card-panel #424242 grey darken-3 center" id="empty-panel">NENHUM REGISTRO ENCONTRADO!</div>
            {% endfor %}
        </tbody>
    </table>

        <div id="representacao"></div>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script>
      Highcharts.chart('representacao', {{ chart|safe }});
    </script>
</div>
{% endblock %}

pesquisasatisfacao/core/templates/person_client_list.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}
{% block container %}

    <div class="card larger" id="card-radius">
        <br>
        <div class="row">
            <form class="col s12">
                <div class="row">
                    <div class="input-field col s12">
                        <input id="searchInput" name="searchInput" type="text" class="validate">
                        <label for="searchInput">Digite sua pesquisa aqui e tecle ENTER.</label>
                    </div>
                </div>
            </form>
        </div>
        <table class="highlight">
            <thead class="#cfd8dc blue-grey lighten-4">
                <tr>
                    <th class="center-align">Id.</th>
                    <th class="center-align">Cód. Alterdata</th>
                    <th>Nome</th>
                    <th class="center-align">Última Pesquisa</th>
                </tr>
            </thead>
            {% for client in clients %}
                <tr>
                    <td class="center-align">
                        <a href="{% url 'person_client_update' pk=client.id %}">{{ client.id|linebreaks }}</a>
                    </td>
                    <td class="center-align">
                        <a href="{% url 'person_client_detail' pk=client.id %}">{{ client.cdalterdata|linebreaks }}</a>
                    </td>
                    <td>
                        {{ client.name|linebreaks }}
                        <!--<a href="{% url 'person_client_detail' pk=client.pk %}">{{ client.name|linebreaks }}</a>-->
                    </td>

                    <td class="center-align">{{ client.last_search }}</td>
                    <!--<td>{{ client.last_search|date:"d/m/Y" }}</td>-->
                </tr>
            {% empty %}
                <div class="card-panel #424242 grey darken-3 center" id="empty-panel">NENHUM REGISTRO ENCONTRADO!</div>
            {% endfor %}
        </table>
    </div>

{% endblock %}

pesquisasatisfacao/core/templates/person_create.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}

{% block container %}

    <div class="card larger" id="card-radius">
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}

            <div class="card-content">
                {% form %}

                {% endform %}
            </div>

            <div class="card-action">
                <div class="right-align">
                    <button class="waves-effect waves-light btn" type="submit">Registrar</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

pesquisasatisfacao/core/templates/person_list.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}
{% block container %}

    <div class="card larger" id="card-radius">
        <table class="highlight">
            <thead class="#cfd8dc blue-grey lighten-4">
                <tr>
                    <th>Id.</th>
                    <th>Cód. Alterdata</th>
                    <th>Nome</th>
                    <th>Telefone</th>
                </tr>
            </thead>
            {% for person in persons %}
                <tr>
                    <td>
                        <a href="{{ person.get_absolute_url }}">{{ person.id|linebreaks }}</a>
                    </td>
                    <td>{{ person.cdalterdata|linebreaks }}</td>
                    <td>{{ person.name|linebreaks }}</td>
                    <td>{{ person.phone|linebreaks }}</td>
                </tr>
            {% empty %}
                <div class="card-panel #424242 grey darken-3 center" id="empty-panel">NENHUM REGISTRO ENCONTRADO!</div>
            {% endfor %}
        </table>
    </div>

{% endblock %}

pesquisasatisfacao/core/templates/question_list.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}
{% block container %}

    <div class="card larger" id="card-radius">
        <table class="highlight">
            <thead class="#cfd8dc blue-grey lighten-4">
                <tr>
                    <th class="center-align">Id.</th>
                    <th>Pergunta</th>
                    <th>Nível</th>
                </tr>
            </thead>
            {% for question in questions %}
                <tr class=" {% if question.get_level_display == 'Dependencia'%}
                                #c5e1a5 light-green lighten-3
                            {% elif question.get_level_display == 'Confianca' %}
                                #bbdefb blue lighten-4
                            {% elif question.get_level_display == 'Comprometimento' %}
                                #ff8a65 deep-orange lighten-2
                            {% elif question.get_level_display == 'Preditiva' %}
                                #e0e0e0 grey lighten-2
                            {% endif %}">

                    <td class="center-align">
                        <a href="{{ question.get_absolute_url }}">{{ question.id|linebreaks }}</a>
                    </td>
                    <td>{{ question.question|linebreaks }}</td>
                    <td>{{ question.get_level_display }}</td>
                </tr>
            {% empty %}
                <div class="card-panel #424242 grey darken-3 center" id="empty-panel">NENHUM REGISTRO ENCONTRADO!</div>
            {% endfor %}
        </table>
    </div>

{% endblock %}

pesquisasatisfacao/core/templates/seach_create.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}

{% block container %}

    <div class="card larger" id="card-radius">
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}

            <div class="card-content">
                {% form %}

                {% endform %}
            </div>

            <div class="card-action">
                <div class="right-align">
                    <button class="waves-effect waves-light btn" type="submit">Registrar</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

pesquisasatisfacao/core/templates/search_funcionando.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}
{% block container %}

    <form method="POST" action=".">
        {% csrf_token %}
        {{ form }}

        <div class="row spacer">
            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-block btn-primary">Create</button>
            </div>
        </div>
    </form>

{% endblock %}