pesquisasatisfacao/accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.i18n import JavaScriptCatalog

from pesquisasatisfacao.accounts import views
from pesquisasatisfacao.accounts.views import GeneratePDF

app_name = 'accounts'


urlpatterns = [
    path('', include('django.contrib.auth.urls')),

    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),

    path('login/', auth_views.auth_login, {'template_name': 'registration/login.html'}, name='login'),
    path('accounts/registro/', views.register, name='register'),

    path('accounts/horario/', views.schedule, name='schedule'),

    path('accounts/ficha/listar/', views.work_schedule_list, name='work_schedule_list'),
    path('accounts/ficha/nova/', views.work_schedule_create, name='work_schedule_create'),
    path('accounts/ficha/<int:id>/editar/', views.work_schedule_update, name='work_schedule_update'),

    path('<int:id>/', GeneratePDF.as_view(), name='generatepdf'),
    path('<int:id>/pdf/', views.admin_receipt_pdf, name='admin_receipt_pdf'),



    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

pesquisasatisfacao/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pesquisasatisfacao.core.urls')),
    path('', include('pesquisasatisfacao.accounts.urls')),
    path('admin/', admin.site.urls),
]

pesquisasatisfacao/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import inlineformset_factory

from pesquisasatisfacao.accounts.models import UserInfo, Horario, WorkSchedule, WorkScheduleItem
from material import *

from pesquisasatisfacao.core.models import Client


class RegistrationForm(forms.Form, UserCreationForm):
    base = forms.ModelChoiceField(queryset=Client.objects.filter(is_representative=True), required=False,
                                  label="Representante (Matriz ou Filial)", )

    class Meta:
        model = UserInfo
        fields = (
            'username',
            'nomecompleto',
            'base',
            'horario',
            'funcao',
        )

    layout = Layout(
        Fieldset('Faça seu cadastro agora.', 'username',
                 Row('password1', 'password2')),
        Fieldset('Dados Pessoais', 'nomecompleto',
                 Row(Span12('base'),),
                 Row(Span12('horario'), ),
                 Row(Span12('funcao'), ),
                 ))


class ScheduleForm(forms.ModelForm):

    class Meta:
        model = Horario
        fields = (
            'description',
            'entrance',
            'lunch_entrance',
            'lunch_out',
            'exit',
        )

    layout = Layout(
        Fieldset('Registro de horário.', 'description',
                 Row('entrance', 'lunch_entrance', 'lunch_out', 'exit')),)


class WorkScheduleForm(forms.ModelForm):

    class Meta:
        model = WorkSchedule
        fields = '__all__'
        exclude = ('user',)

    layout = Layout(
        Fieldset("Preencha com o Período",
                 Row('period'),),)


WorkScheduleItemFormSet = inlineformset_factory(WorkSchedule, WorkScheduleItem,
                                                exclude=('id',),
                                                can_delete=True,
                                                fields=('day', 'week_day', 'entrance', 'lunch_entrance', 'lunch_out', 'exit'),
                                                extra=0)

pesquisasatisfacao/accounts/views.py
import calendar
import datetime
import random

import weasyprint
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings

# Create your views here.
from django.template.loader import render_to_string, get_template
from django.views import View

from pesquisasatisfacao.accounts.forms import (RegistrationForm,
                                               ScheduleForm,
                                               WorkScheduleForm,
                                               WorkScheduleItemFormSet)

from pesquisasatisfacao.accounts.models import WorkSchedule, WorkScheduleItem, Feriado, Compensacao
from pesquisasatisfacao.utils import render_to_pdf


def random_time():
    entra = random.randint(8, 9)
    almoco = random.randint(entra + 3, 13)

    if entra == 8:
        value_en = str(entra).zfill(2) + ':' + str(random.randint(45, 59)).zfill(2)
    else:
        value_en = str(entra).zfill(2) + ':' + str(random.randint(0, 14)).zfill(2)
    # -------------------------------------------------------------------------------------

    if almoco == 11:
        value_ea = str(almoco).zfill(2) + ':' + str(random.randint(45, 59)).zfill(2)
    elif almoco != 11:
        value_ea = str(almoco).zfill(2) + ':' + str(random.randint(0, 14)).zfill(2)

    # -------------------------------------------------------------------------------------

    if value_ea == 11:
        value_va = str(almoco + 1).zfill(2) + ':' + str(random.randint(45, 59)).zfill(2)
    elif value_ea != 12:
        value_va = str(almoco + 1).zfill(2) + ':' + str(random.randint(0, 14)).zfill(2)

    # -------------------------------------------------------------------------------------

    if almoco == 11:
        value_out = str(almoco + 7).zfill(2) + ':' + str(random.randint(0, 14)).zfill(2)
    elif almoco == 12:
        value_out = str(almoco + 6).zfill(2) + ':' + str(random.randint(0, 14)).zfill(2)
    elif almoco == 13:
        value_out = str(almoco + 5).zfill(2) + ':' + str(random.randint(0, 14)).zfill(2)

    return value_en, value_ea, value_va, value_out


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)

        if form.is_valid():
            print('<<<<==== FORM VALIDO ====>>>>')
            new = form.save(commit=False)
            new.save()
            #form.save_m2m()

            return redirect(settings.LOGIN_URL)
        else:
            print('<<<<==== AVISO DE FORMULARIO INVALIDO ====>>>>')
            return render(request, 'register.html', {'form': form})
    else:
        context = {'form': RegistrationForm()}
        return render(request, 'register.html', context)


def schedule(request):
    if request.method == 'POST':
        form = ScheduleForm(request.POST)

        if form.is_valid():
            print('<<<<==== FORM VALIDO ====>>>>')
            new = form.save(commit=False)
            new.save()
            #form.save_m2m()

            return redirect(settings.LOGIN_REDIRECT_URL)
        else:
            print('<<<<==== AVISO DE FORMULARIO INVALIDO ====>>>>')
            return render(request, 'schedule.html', {'form': form})
    else:
        context = {'form': ScheduleForm()}
        return render(request, 'schedule.html', context)


def add_work_schedule_item(period, key, feriado_user):
    year_month = str(period)
    m, y = year_month.split('/')
    first_weekday, num_days_in_month = calendar.monthrange(int(y), int(m))
    work_schedule = get_object_or_404(WorkSchedule, pk=key)

    for day_number in range(1, num_days_in_month + 1):
        strdate = datetime.datetime(int(y), int(m), day_number)
        my_date = calendar.weekday(int(y), int(m), day_number)
        # my_date = calendar.day_name[strdate.weekday()]

        (value_en, value_ea, value_va, value_out) = random_time()

        ad = str(day_number).zfill(2) + '/' + m.zfill(2)
        sabado = Compensacao.objects.prefetch_related().filter(abbreviated_date=ad, users=feriado_user)
        feriado = Feriado.objects.prefetch_related().filter(abbreviated_date=ad)

        # Se a data cadastrada coincidir com feríados e compensação cadastrados via Admin
        # Ele preenche com 7 ou 9 e trata lá no template
        if sabado:
            for s in sabado:
                # if e.kind == '9':
                WorkScheduleItem.objects.get_or_create(day=strdate,
                                                       week_day=s.kind,
                                                       workschedule=work_schedule,
                                                       entrance=value_en,
                                                       lunch_entrance=value_ea,
                                                       lunch_out=value_va,
                                                       exit=value_out)
        elif feriado:
            for f in feriado:
                WorkScheduleItem.objects.get_or_create(day=strdate,
                                                       week_day=f.kind,
                                                       workschedule=work_schedule,
                                                       entrance=value_en,
                                                       lunch_entrance=value_ea,
                                                       lunch_out=value_va,
                                                       exit=value_out)
        else:
            if my_date not in (5, 6, 7):
                WorkScheduleItem.objects.get_or_create(day=strdate,
                                                       week_day=my_date,
                                                       workschedule=work_schedule,
                                                       entrance=value_en,
                                                       lunch_entrance=value_ea,
                                                       lunch_out=value_va,
                                                       exit=value_out)
            else:
                WorkScheduleItem.objects.get_or_create(day=strdate,
                                                       week_day=my_date,
                                                       workschedule=work_schedule,
                                                       )


def work_schedule_create(request):
    # Cria variável na session
    request.session['person_id'] = 1

    if request.method == 'POST':
        form = WorkScheduleForm(request.POST)

        if form.is_valid():
            print('<<<<==== FORM VALIDO ====>>>>')
            new = form.save(commit=False)
            new.user = request.user
            new.save()
            # form.save_m2m()
            a, b, c, my_id, e, f = new.get_absolute_url().split('/')
            add_work_schedule_item(period=request.POST['period'], key=my_id, feriado_user=request.user)

            return HttpResponseRedirect('/accounts/ficha/' + str(new.id) + '/editar/')
        else:
            print('<<<<==== AVISO DE FORMULARIO INVALIDO ====>>>>')
            return render(request, 'work_schedule_create.html', {'form': form})
    else:
        from datetime import date
        context = {'form': WorkScheduleForm(initial={'user': request.user,
                                                     'period': date.today().strftime('%m/%Y')})}        # Caso precise preencher mais de um campo no form.
        # context = {'form': SearchForm(initial={'person': pessoa_id, 'search_key': '11-2018'})}

        # Exclui variável da session
        del request.session['person_id']

        return render(request, 'work_schedule_create.html', context)


def work_schedule_update(request, id):
    # Pega a chave da URL acima com (request, pk)
    # joga na variável invoice na linha abaixo passando o modelo MESTRE e os parâmetros que desejo como filtro
    work_schedule = get_object_or_404(WorkSchedule, id=id)
    # print(request.method)
    if request.method == 'POST':
        # Os formulários InvoiceForm receberá o request.POST com os campos em branco
        form = WorkScheduleForm(request.POST, instance=work_schedule)
        formset = WorkScheduleItemFormSet(request.POST, instance=work_schedule)

        # Valida os formulários MESTRE(WorkScheduleForm) e DETALHE(WorkScheduleItemFormSet)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            return redirect('/accounts/ficha/listar/')
    else:
        # Caso não seja POST ele trará o formulário com as informações preenchidas do parâmetro invoice
        # que pegamos da URL quando passamos o request de pk na entrada da função acima.
        form = WorkScheduleForm(instance=work_schedule)
        # Recupera a instancia de form e chama a função add_work_schedule_item
        # para popular o detalhe com os dias do mês e o usuário poderá editar.
        # add_work_schedule_item(period=work_schedule.period, key=work_schedule.id)

        formset = WorkScheduleItemFormSet(instance=work_schedule)

    # Passamos os dois forms para uma variável com um nome qualquer (Neste caso usamos o nome "forms" afim de dar
    # a idéia
    # de mais de um formulário conforme abaixo:
    # Na linha context passamos também os dois contextos e
    # por fim na linha final passamos o retorno da função onde chamamos o template com o context.
    forms = [formset.empty_form] + formset.forms
    context = {'form': form, 'formset': formset, 'forms': forms}
    return render(request, 'visita_form.html', context)


def admin_receipt_pdf(request, id=id):
    work_schedule = WorkSchedule.objects.select_related('user__userinfo').get(id=id)
    work_schedule_itens = WorkScheduleItem.objects.select_related('workschedule').filter(workschedule_id=id)\
        .order_by('day')

    print(work_schedule_itens.query)

pesquisasatisfacao/accounts/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}

{% block container %}

    <div class="card larger" id="card-radius">
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}

            <div class="card-content">
                {% form %}
                    {% part form.username prefix %}<i class="material-icons prefix">account_box</i>{% endpart %}

                    {% part form.password prefix %}<i class="material-icons prefix">lock</i>{% endpart %}
                {% endform %}
            </div>

            <div class="card-action">
                <div class="right-align">
                    <button class="waves-effect waves-light btn" type="submit">Logar</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

pesquisasatisfacao/accounts/templates/register.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}

{% block container %}

    <div class="card larger" id="card-radius">
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}

            <div class="card-content">
                {% form %}
                        {% part form.username prefix %}<i class="material-icons prefix">person</i>{% endpart %}
                        {% part form.password1 prefix %}<i class="material-icons prefix">lock</i>{% endpart %}
                        {% part form.password2 prefix %}<i class="material-icons prefix">lock</i>{% endpart %}
                {% endform %}
            </div>

            <div class="card-action">
                <div class="right-align">
                    <button class="waves-effect waves-light btn" type="submit">Registrar-se</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

pesquisasatisfacao/accounts/templates/schedule.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}

{% block container %}

    <div class="card larger" id="card-radius">
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}

            <div class="card-content">
                {% form %}

                {% endform %}
            </div>

            <div class="card-action">
                <div class="right-align">
                    <button class="waves-effect waves-light btn" type="submit">Registrar</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

pesquisasatisfacao/accounts/templates/schedule_list.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}
{% block container %}

    <div class="card larger" id="card-radius">
        <br>
        <div class="row">
            <form class="col s12">
                <div class="row">
                    <div class="input-field col s12">
                        <input id="searchInput" name="searchInput" type="text" class="validate">
                        <label for="searchInput">Digite o período aqui e tecle ENTER.</label>
                    </div>
                </div>
            </form>
        </div>
        <table class="highlight">
            <thead class="#cfd8dc blue-grey lighten-4">
                <tr>
                    <th class="left-align">Id</th>
                    <th class="left-align">Período</th>
                    <th class="left-align">Usuário</th>
                    <th></th>
                </tr>
            </thead>
            {% for work_schedule in work_schedules %}
                <tr>
                    <td class="center-align">
                        <a>{{ work_schedule.id|linebreaks }}</a>
                    </td>
                    <td class="center-align">
                        <a href="{% url 'accounts:work_schedule_update' id=work_schedule.id %}">{{ work_schedule.period|linebreaks }}</a>
                    </td>
                    <td>
                        {{ work_schedule.user|linebreaks }}
                    </td>
                    <td><a href="{% url 'accounts:admin_receipt_pdf' id=work_schedule.id %}"><i class="small material-icons">local_printshop</i></a></td>

                </tr>
            {% empty %}
                <div class="card-panel #424242 grey darken-3 center" id="empty-panel">NENHUM REGISTRO ENCONTRADO!</div>
            {% endfor %}
        </table>
    </div>

{% endblock %}

pesquisasatisfacao/accounts/templates/schedule_report.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'core/css/css.css' %}"/>
	<meta charset="UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
	<form class="container clearfix">

		<h1>HORÁRIO DE TRABALHO EXTERNO<br/>FICHA INDIVIDUAL</h1>
        <img class="img-topo" src="{% static 'img/logo.png' %}">
		<div class="text_justificado">
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    Nome da Firma: <strong><label name="recebido" class="recebido">{{work_schedule.user.userinfo.base|upper}}</label></strong>
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    CNPJ: <strong><label name="recebido" class="recebido">{{work_schedule.user.userinfo.base.cpf_cnpj|upper}}</label></strong>
                                    <label>______</label>Atividade: ________________________________________________
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Endereço: <strong>
                                                    <label name="recebido" class="recebido">{{work_schedule.user.userinfo.base.logradouro|upper}}</label>,
                                                    <label name="recebido" class="recebido">{{work_schedule.user.userinfo.base.numero|upper}}</label>,
                                                    <label name="recebido" class="recebido">{{work_schedule.user.userinfo.base.bairro|upper}}</label>,
                                                    <label name="recebido" class="recebido">{{work_schedule.user.userinfo.base.cidade|upper}}</label>/
                                                    <label name="recebido" class="recebido">{{work_schedule.user.userinfo.base.estado|upper}}</label>
                                              </strong>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Nome do Empregado: <strong><label name="recebido" class="recebido">{{work_schedule.user.userinfo.nomecompleto|upper}}</label></strong>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Carteira Profissional: <strong>______________________Série:______________</label></strong>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Função: <strong><label name="recebido" class="recebido">{{work_schedule.user.userinfo.funcao|upper}}</label></strong>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Horário de trabalho: <strong><label name="recebido" class="recebido">{{work_schedule.user.userinfo.horario|upper}}</label></strong>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Descanso Semanal: <strong>_____SÁB/DOM______________________________</label></strong>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Período de Validade: <strong><label name="recebido" class="recebido">{{work_schedule.period|upper}}</label></strong>
                                </td>
                            </tr>
                        </tbody>

                    </table>

                    <table>
                        <thead class="cabecalho-tabela">
                            <tr>
                                <th rowspan="2">Dia</th>
                                <th rowspan="2">Entrada</th>

                                <th colspan="2">Almoço</th>

                                <th rowspan="2">Saída</th>
                                <th colspan="2">Visto do fiscal</th>

                            </tr>

                            <tr>

                                <th>Entrada</th>

                                <th>Saída</th>

                                <th>Data</th>
                                <th>Assinatura</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for work_schedule_item in work_schedule_itens %}
                                {% if work_schedule_item.week_day == '5' %}
                                    <tr>
                                        <td>{{ work_schedule_item.day|date:"d" }}</td>
                                        <th colspan="4">Sábado</th>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                {% elif work_schedule_item.week_day == '6' %}
                                    <tr>
                                        <td>{{ work_schedule_item.day|date:"d" }}</td>
                                        <th colspan="4">Domingo</th>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                {% elif work_schedule_item.week_day == '7' %}
                                    <tr>
                                        <td>{{ work_schedule_item.day|date:"d" }}</td>
                                        <th colspan="4">Feriado</th>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                {% elif work_schedule_item.week_day == '8' %}
                                    <tr>
                                        <td>{{ work_schedule_item.day|date:"d" }}</td>
                                        <th colspan="4">Faltou</th>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td>{{ work_schedule_item.day|date:"d" }}</td>
                                        <!--<td>{{ work_schedule_item.day|date:"l" }}</td>-->
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                {% endif %}
                            {% empty %}
                                <li>
                                    Sem registros
                                </li>
                            {% endfor %}
                        </tbody>
                    </table>
		</div>
	</form>

    <footer>
        <br>
        <div class="center">
            <strong><label name="recebido" class="recebido">___________________________________________</label></strong>
        </div>
        <div class="center">
            <strong><label name="recebido" class="recebido">Assinatura do Empregado</label></strong>
        </div>
        <br>
        <div class="center">
            <strong><label name="recebido" class="recebido">___________________________________________</label></strong>
        </div>
        <div class="center">
            <strong><label name="recebido" class="recebido">Assinatura do Empregador</label></strong>
        </div>

    {#  <p>Posted by: Hege Refsnes</p>#}
    {#  <p>Contact information: <a href="mailto:someone@example.com">someone@example.com</a>.</p>#}
    </footer>
</body>
</html>

pesquisasatisfacao/accounts/templates/visita_form.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}
{% load i18n %}
{% block container %}

<div class="card larger" id="card-radius">

    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="card-content">
                {% form %}

                {% endform %}
            </div>

        <div class="card-content">
            <table class="highlight table-especial">
                <thead class="#cfd8dc blue-grey lighten-4">
                    <tr>
                        <th class="left-align">Dia semana</th>
                        <th class="left-align">Dia</th>
                        <th class="left-align">Entrada</th>
                        <th class="left-align">Entrada Almoço</th>
                        <th class="left-align">Volta Almoço</th>
                        <th class="left-align">Saída</th>
                        <th></th>
                    </tr>
                </thead>

                {{ formset.management_form }}

                <tbody>
                    {% for item_form in formset %}

                          <tr class=" {% if item_form.week_day.value == '5' %}
                                            #c5e1a5 light-green lighten-3
                                        {% elif item_form.week_day.value == '6' %}
                                            #bbdefb blue lighten-4
                                        {% elif item_form.week_day.value == '7' %}
                                            #ff8a65 deep-orange lighten-2
                                        {% elif item_form.week_day.value == '8' %}
                                            #e0e0e0 grey lighten-2
                                        {% else %}
                                            item_form.week_day.value
                                        {% endif %}">
                                <td>{{ item_form.week_day.errors }} {{ item_form.week_day }}</td>
                                <td>{{ item_form.day.errors }} {{ item_form.day }}</td>
                                <td>{{ item_form.entrance.errors }} {{ item_form.entrance }}</td>
                                <td>{{ item_form.lunch_entrance.errors }} {{ item_form.lunch_entrance }}</td>
                                <td>{{ item_form.lunch_out.errors }} {{ item_form.lunch_out }}</td>
                                <td>{{ item_form.exit.errors }} {{ item_form.exit }}</td>
                                <td>{{ item_form.id.errors }} {{ item_form.id }}</td>
                          </tr>

                    {% endfor %}

                </tbody>

            </table>

        </div>


        <br><br>

            <div class="card-action">
                <div class="right-align">
                    <button name="btn_submit" class="waves-effect waves-light btn" type="submit">Imprimir</button>
                </div>
            </div>
    </form>


</div>

{% endblock %}

        <script src="{% static 'js/jquery.formset.min.js' %}"></script>
        <script src="{% static 'js/invoice_form.js' %}"></script>

pesquisasatisfacao/accounts/templates/work_schedule_create.html
{% extends "base.html" %}
{% load static %}
{% load material_form %}

{% block container %}

    <div class="card larger" id="card-radius">
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}

            <div class="card-content">
                {% form %}

                {% endform %}
            </div>

            <div class="card-action">
                <div class="right-align">
                    <button class="waves-effect waves-light btn" type="submit">Registrar</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}